config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :roomtypes
  resources :reviews
  root 'posts#index'
  resources :posts
  devise_for :users , controllers: {
      sessions: 'users/sessions',
     passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  
  devise_scope :user do 
    get 'users/host' => 'users/registrations#host' 
    get 'users/tohost' => 'users/registrations#tohost'
    end

end

app/controllers/roomtypes_controller.rb
class RoomtypesController < ApplicationController
  before_action :set_roomtype, only: [:show, :edit, :update, :destroy]

  # GET /roomtypes
  # GET /roomtypes.json
  def index
    @roomtypes = Roomtype.all
  end

  # GET /roomtypes/1
  # GET /roomtypes/1.json
  def show
  end

  # GET /roomtypes/new
  def new
    @roomtype = Roomtype.new
  end

  # GET /roomtypes/1/edit
  def edit
  end

  # POST /roomtypes
  # POST /roomtypes.json
  def create
    @roomtype = Roomtype.new(roomtype_params)

    respond_to do |format|
      if @roomtype.save
        format.html { redirect_to @roomtype, notice: 'Roomtype was successfully created.' }
        format.json { render :show, status: :created, location: @roomtype }
      else
        format.html { render :new }
        format.json { render json: @roomtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roomtypes/1
  # PATCH/PUT /roomtypes/1.json
  def update
    respond_to do |format|
      if @roomtype.update(roomtype_params)
        format.html { redirect_to @roomtype, notice: 'Roomtype was successfully updated.' }
        format.json { render :show, status: :ok, location: @roomtype }
      else
        format.html { render :edit }
        format.json { render json: @roomtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roomtypes/1
  # DELETE /roomtypes/1.json
  def destroy
    @roomtype.destroy
    respond_to do |format|
      format.html { redirect_to roomtypes_url, notice: 'Roomtype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roomtype
      @roomtype = Roomtype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roomtype_params
      params.require(:roomtype).permit(:type)
    end
end

app/helpers/roomtypes_helper.rb
module RoomtypesHelper
end

app/views/roomtypes/_form.html.erb
<%= form_for(@roomtype) do |f| %>
  <% if @roomtype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roomtype.errors.count, "error") %> prohibited this roomtype from being saved:</h2>

      <ul>
      <% @roomtype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roomtypes/edit.html.erb
<h1>Editing Roomtype</h1>

<%= render 'form' %>

<%= link_to 'Show', @roomtype %> |
<%= link_to 'Back', roomtypes_path %>

app/views/roomtypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Roomtypes</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roomtypes.each do |roomtype| %>
      <tr>
        <td><%= roomtype.type %></td>
        <td><%= link_to 'Show', roomtype %></td>
        <td><%= link_to 'Edit', edit_roomtype_path(roomtype) %></td>
        <td><%= link_to 'Destroy', roomtype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roomtype', new_roomtype_path %>

app/views/roomtypes/new.html.erb
<h1>New Roomtype</h1>

<%= render 'form' %>

<%= link_to 'Back', roomtypes_path %>

app/views/roomtypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @roomtype.type %>
</p>

<%= link_to 'Edit', edit_roomtype_path(@roomtype) %> |
<%= link_to 'Back', roomtypes_path %>