config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :roomtypes
  resources :reviews
  root 'posts#index'
  resources :posts
  devise_for :users , controllers: {
      sessions: 'users/sessions',
     passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  
  devise_scope :user do 
    get 'users/host' => 'users/registrations#host' 
    get 'users/tohost' => 'users/registrations#tohost'
    end

end

app/models/post.rb
class Post < ActiveRecord::Base
    mount_uploader :post_picture, PostUploader
    belongs_to :user
    has_many :reviews, -> { order "created_at DESC"}
    has_one :roomtype
    has_many :post_comment#, ->{ order "create_at DESC"}
    def self.search(search)
        where("post_city LIKE ?", "%#{search}%")
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def new
    @post = Post.new
  end

  def index
    @post = Post.all
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.all.order('created_at DESC')
    end
  end

  def show
  end
  
  def create
    @post = Post.new(permit_post)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
      
  end
  
  private
  def set_post
    @post = Post.find(params[:id])
  end
    def permit_post
        params.require(:post).permit(:post_road,:post_city,:post_district,:post_roomtype,:post_price,:post_phone,:post_intro,:post_picture)
    end
  
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<h1>Listing Home</h1>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<div class="container">
    <div class="row">
        <% @post.each do |post| %>
        <div class="col-md-4">
            <div class="ui card">
                <div class="thumbnail">

                    <%= image_tag post.post_picture  %>
                </div>
                <div class ="content">
                  <%= link_to 'Address: '+post.post_road+', '+post.post_district+', '+post.post_city, post, class:"header" %>
                <div class="description">
						      Phone: <%= post.post_phone %><br>
						      Price: <%= post.post_price %>¥
					      </div>
          			</div>
          			</div>

                </div>
                
            </div>
        </div>
        <% end %>
        

app/views/posts/new.html.erb
<h1>New Post</h1>
<hr>

<%= form_for(@post, {multipart: true}) do |f| %>
    <div class="field form-group">
      <%= f.label :address %><br />
      <%= f.text_area :post_road, class:"form-control",placeholder:"Road",style:"width:60%" %>
      <%= f.text_area :post_district, class:"form-control",placeholder:"District",style:"width:60%" %>
      <%= f.text_area :post_city, class:"form-control",placeholder:"City",style:"width:60%" %>
    </div>
    <br/>
 
    <div class="field form-group">
      <%= f.label :price %><br />
      <%= f.number_field :post_price,class:"form-control",placeholder:"Price",style:"width:25%"%>
    </div>
    
    <div class="field form-group">
      <%= f.label :roomtype %><br />
      <%= select_tag :roomtype, "<option value='Vila'>Vila</option><option value='Apartment'>Apartment</option><option value='Single Room'>Single Room</option>".html_safe  %>

    </div>
    
    <br />

    <div class="field form-group">
      <%= f.label :phone %><br />
      <%= f.text_field :post_phone,class:"form-control",placeholder:"Phone" ,style:"width:25%"%>
    </div>

    <div class="field form-group">
      <%= f.label :description %>
      <%= f.text_area :post_intro,rows:"5", autocomplete: "off",class:"form-control",placeholder:"Describe",style:"width:60%" %>
    </div>

    <div class="field form-group">
      <%= f.label :picture %><br />
      <%= f.file_field :post_picture,class:"form-control" ,style:"width:60%"%>
    </div>

    <div class="actions">
      <%= f.submit "Create Post",class:"btn btn-default" %>
    </div>

<% end %>

app/views/posts/root.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>
<h1>Listing Books</h1>

<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>post_address</th>
    <th>post_intro</th>
    <th>post_price</th>
    <th>post_phone</th>
    <th>post_picture</th>
    <th>user_id</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @post.each do |post| %>
      <tr>
        <td><%=  %></td>
        <td><%= post.post_address %></td>
        <td><%= post.post_intro %></td>

        <td><%= post.post_price %></td>
        <td><%= post.post_phone %></td>
        <td><%= post.post_picture %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/posts/show.html.erb
<div style="padding: 20px;float: left; width: 60%;" class=".col-xs-12 .col-sm-6 .col-md-8" >

  <span><%= @post.user_id %></span>
  <span style="float: right; border-radius: 1000px; border: 1px solid black; padding: 5px"><%= @post.user_id %></span>
    
    <hr>
  <div>
    <p ><%= @post.post_roomtype%></p>
  </div>
  <hr>
  <hr>
  <div>
    <p ><%= @post.post_road %>, <%= @post.post_district %>, <%= @post.post_city %></p>
  </div>
  <hr>
  
  <hr>
  <div>
    <p ><%= @post.post_intro %></p>
  </div>
  <hr>
</div>
<div class=".col-xs-6 .col-md-4" style="width: 40%;float: right">
  <div style="height: 400px;width:100%;background-color: #FFE623">
  
      <%= image_tag @post.post_picture, style:"height: 400px;width:100%" %>
  </div>
  <hr>
  <div align="center">
    <h3><%= @post.post_price %> ¥</h3>
    <h4>Phone: <%= @post.post_phone %></h4>
  </div>
</div>
 