config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :roomtypes
  resources :reviews
  root 'posts#index'
  resources :posts
  devise_for :users , controllers: {
      sessions: 'users/sessions',
     passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  
  devise_scope :user do 
    get 'users/host' => 'users/registrations#host' 
    get 'users/tohost' => 'users/registrations#tohost'
    end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © <%= link_to "HomeTel" %>, Inc.
  </small>
  <nav>
    <ul>
      <li><%= link_to "Terms",   '#' %></li>
      <li><%= link_to "Privacy", '#' %></li>
      <li><%= link_to "Site Map", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "HomeTel", root_url, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%- if current_user %>
        <form class="navbar-form navbar-left">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search by Address">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </div>
            </div>
        </form>
      <% end %>
      <ul class="nav navbar-nav pull-right">
        <%- if current_user.try(:host_role?) %>
        <li>
          <%= link_to "New Post", new_post_path %>
        </li>
        <% end %>
        
        <%- if current_user.try(:user_role?) && current_user.try(:host_role) == false %>
        <li>
          <%= link_to "Become A Host", users_host_path %>
        </li>
        <% end %>
        <%- if current_user %>
            <li>
              <%= link_to "Profile", edit_user_registration_path %>
            </li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, confirm: "Are you sure?" %>
            </li>
        <% else %>
            <li>
              <%= link_to "Signup", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "Login", new_user_session_path %>

            </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<!-- Page Content -->
<div class="container main-content">

  <div class="row">
    <div class="col-lg-12">
      <% flash.each do |a, b| %>
          <div class="alert alert-success">
            <%= b %>
          </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
  <!-- /.row -->
</div>

<div class="footer container">
  <%= render 'layouts/footer' %>
</div>

<style>
  body {
    padding-top: 70px;
    /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
  }

</style>

</body>

</html>